#[cfg(feature = "agent-runtime")]
pub mod auth;
#[cfg(feature = "agent-runtime")]
pub mod config;
#[cfg(feature = "agent-runtime")]
pub mod desktop;
#[cfg(feature = "agent-runtime")]
pub mod eval;
#[cfg(feature = "plugins-wasm")]
pub mod plugin;
#[cfg(feature = "agent-runtime")]
pub mod quickstart;
#[cfg(feature = "agent-runtime")]
pub mod self_test;
#[cfg(feature = "agent-runtime")]
pub mod status;
#[cfg(all(feature = "agent-runtime", feature = "channel-telegram"))]
pub mod telegram;
pub mod update;
